# example netlify.toml
[build]
command = "npm run build"
functions = "functions/src"
publish = "app/dist"

## Uncomment to use this redirect for Single Page Applications like create-react-app.
## Not needed for static site generators.
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[functions]
node_bundler = "esbuild"
directory = "functions/src/"

## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
[dev]
  port = 8080 # Port that the dev server will be listening on
  framework = "vite"
  targetPort = 5174

[build.environment]
NODE_VERSION = "18.17.1"
NPM_VERSION = "9.6.7"

## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/
