name: Lint
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.1
    - uses: actions/setup-node@v4.0.4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Run Linter
      run: npm run lint